version: "3.5"

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ui_net
      - nginx-net

  ui:
    image: node:10
    working_dir: "/opt/app"
    ports:
      - "18001:8000"
    volumes:
      - ./:/opt/app:rw
    command: sh -c "test -d node_modules && npm start || (npm install && npm start)"
    networks:
      - ui_net

networks:
  ui_net:
  nginx-net:
    external: true