version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
      - wp-net
     
   wordpress:
     image: wordpress:latest
     ports:
       - 9000
     restart: always
     environment:
       VIRTUAL_HOST: blog.thiswjk.xyz
       VIRTUAL_PORT: 8080
       LETSENCRYPT_HOST: blog.thiswjk.xyz
       LETSENCRYPT_EMAIL: kangmang92@gmail.com
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
      - wp-net
      - nginx-net

volumes:
    db_data:
    
networks:
  wp-net:
  nginx-net:
    external: true