version: 2
jobs:
  build:
    working_directory: /ui
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/ui.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/ui.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t ui .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/ui.tar ui
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ui.tar
      - run:
          name: Push to registry
          command: |
            docker login registry.thiswjk.xyz -u ${user} -p ${passd}
            docker tag ui registry.thiswjk.xyz/will/ui
            docker push registry.thiswjk.xyz/will/ui
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: update service
          command: |
            curl -X POST ${web_webhooks}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master