version: "3"

services:

  db:
    image: mysql:5.7
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  web:
    build: ./main
    ports:
    - "8000:8000"
    volumes:
    - ./:/mysite
    - /tmp/logs:/tmp
    command: bash start.sh  # 执行命令，有多种格式
    links:
    - db
    depends_on:
    - db
    restart: always

  nginx:
    build: ./config
    ports:
    - "80:80"
    volumes:
    - ./static:/usr/share/nginx/html/static:ro
    links:
    - web
    depends_on:
    - web
    restart: always