version: "3"
services:
  registry:
    image: registry:2
    environment:
      VIRTUAL_HOST: registry.thiswjk.xyz
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: registry.thiswjk.xyz
      LETSENCRYPT_EMAIL: kangmang92@gmail.com
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/.passwd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth
    networks:
      - nginx-net
volumes:
  registry_auth:
    external:
      name: registry_auth
  registry_data:
    external:
      name: registry_data

networks:
  nginx-net:
    external: true
